/**
 * Wu Xing (Five Elements) and Chinese Zodiac data
 */

export const ELEMENT_CONFIG = {
  Wood: {
    glyph: '🌿',
    glyphClass: 'element-glyph-wood',
    badgeClass: 'badge-wood',
    keyword: 'The Grower',
    desc: 'Wood energy drives expansion, vision, and upward momentum. Your signal has a natural growth orientation — you see potential before it has form and move toward it instinctively.'
  },
  Fire: {
    glyph: '🔥',
    glyphClass: 'element-glyph-fire',
    badgeClass: 'badge-fire',
    keyword: 'The Igniter',
    desc: 'Fire energy drives transformation, intensity, and presence. Your signal radiates outward and draws others in. You do not just participate in moments — you create them.'
  },
  Earth: {
    glyph: '🌍',
    glyphClass: 'element-glyph-earth',
    badgeClass: 'badge-earth',
    keyword: 'The Anchor',
    desc: 'Earth energy drives stability, nourishment, and centering. Your signal grounds everything around it. People and situations naturally stabilize in your presence.'
  },
  Metal: {
    glyph: '⚡',
    glyphClass: 'element-glyph-metal',
    badgeClass: 'badge-metal',
    keyword: 'The Refiner',
    desc: 'Metal energy drives precision, clarity, and strength under pressure. Your signal cuts through noise. You see what matters and remove what does not.'
  },
  Water: {
    glyph: '💧',
    glyphClass: 'element-glyph-water',
    badgeClass: 'badge-water',
    keyword: 'The Flow',
    desc: 'Water energy drives depth, adaptability, and wisdom. Your signal moves around obstacles rather than through them. You find the path others miss because you follow what is natural, not what is forced.'
  }
};

export const ELEMENT_AXIOMS = {
  Wood: 'Energy moves by growing toward light. Wood is directional — it always orients toward expansion, upward movement, and new possibility. Its operating principle is vision in motion.',
  Fire: 'Energy moves by radiating outward and illuminating connection. Fire transforms everything it contacts and makes people visible to each other. Its operating principle is transformation through connection.',
  Earth: 'Energy moves by centering and integrating. Earth is the only element without a single directional flow — it sits at the center and makes transitions between all other elements possible. Its operating principle is integration through presence.',
  Metal: 'Energy moves by refining and clarifying. Metal cuts through what is unnecessary to reveal what is essential. It does not add — it removes until only what matters remains. Its operating principle is precision through reduction.',
  Water: 'Energy moves by finding the path of least resistance and accumulating depth. Water carries accumulated wisdom from everything it has passed through, including fear as signal rather than weakness. Its operating principle is wisdom through depth.'
};

/**
 * Chinese Zodiac lookup table
 * Each year has a lunar new year date; birthdays on/after that date use that year's animal
 * Birthdays before that date use the previous year's animal
 */
export const CHINESE_ZODIAC = [
  { year: 1900, month: 1, day: 31, animal: "Rat", element: "Metal" },
  { year: 1901, month: 2, day: 19, animal: "Ox", element: "Metal" },
  { year: 1902, month: 2, day: 8, animal: "Tiger", element: "Water" },
  { year: 1903, month: 1, day: 29, animal: "Rabbit", element: "Water" },
  { year: 1904, month: 2, day: 16, animal: "Dragon", element: "Wood" },
  { year: 1905, month: 2, day: 4, animal: "Snake", element: "Wood" },
  { year: 1906, month: 1, day: 25, animal: "Horse", element: "Fire" },
  { year: 1907, month: 2, day: 13, animal: "Goat", element: "Fire" },
  { year: 1908, month: 2, day: 2, animal: "Monkey", element: "Earth" },
  { year: 1909, month: 1, day: 22, animal: "Rooster", element: "Earth" },
  { year: 1910, month: 2, day: 10, animal: "Dog", element: "Metal" },
  { year: 1911, month: 1, day: 30, animal: "Pig", element: "Metal" },
  { year: 1912, month: 2, day: 18, animal: "Rat", element: "Water" },
  { year: 1913, month: 2, day: 6, animal: "Ox", element: "Water" },
  { year: 1914, month: 1, day: 26, animal: "Tiger", element: "Wood" },
  { year: 1915, month: 2, day: 14, animal: "Rabbit", element: "Wood" },
  { year: 1916, month: 2, day: 3, animal: "Dragon", element: "Fire" },
  { year: 1917, month: 1, day: 23, animal: "Snake", element: "Fire" },
  { year: 1918, month: 2, day: 11, animal: "Horse", element: "Earth" },
  { year: 1919, month: 2, day: 1, animal: "Goat", element: "Earth" },
  { year: 1920, month: 2, day: 20, animal: "Monkey", element: "Metal" },
  { year: 1921, month: 2, day: 8, animal: "Rooster", element: "Metal" },
  { year: 1922, month: 1, day: 28, animal: "Dog", element: "Water" },
  { year: 1923, month: 2, day: 16, animal: "Pig", element: "Water" },
  { year: 1924, month: 2, day: 5, animal: "Rat", element: "Wood" },
  { year: 1925, month: 1, day: 25, animal: "Ox", element: "Wood" },
  { year: 1926, month: 2, day: 13, animal: "Tiger", element: "Fire" },
  { year: 1927, month: 2, day: 2, animal: "Rabbit", element: "Fire" },
  { year: 1928, month: 1, day: 23, animal: "Dragon", element: "Earth" },
  { year: 1929, month: 2, day: 10, animal: "Snake", element: "Earth" },
  { year: 1930, month: 1, day: 30, animal: "Horse", element: "Metal" },
  { year: 1931, month: 2, day: 17, animal: "Goat", element: "Metal" },
  { year: 1932, month: 2, day: 6, animal: "Monkey", element: "Water" },
  { year: 1933, month: 1, day: 26, animal: "Rooster", element: "Water" },
  { year: 1934, month: 2, day: 14, animal: "Dog", element: "Wood" },
  { year: 1935, month: 2, day: 4, animal: "Pig", element: "Wood" },
  { year: 1936, month: 1, day: 24, animal: "Rat", element: "Fire" },
  { year: 1937, month: 2, day: 11, animal: "Ox", element: "Fire" },
  { year: 1938, month: 1, day: 31, animal: "Tiger", element: "Earth" },
  { year: 1939, month: 2, day: 19, animal: "Rabbit", element: "Earth" },
  { year: 1940, month: 2, day: 8, animal: "Dragon", element: "Metal" },
  { year: 1941, month: 1, day: 27, animal: "Snake", element: "Metal" },
  { year: 1942, month: 2, day: 15, animal: "Horse", element: "Water" },
  { year: 1943, month: 2, day: 5, animal: "Goat", element: "Water" },
  { year: 1944, month: 1, day: 25, animal: "Monkey", element: "Wood" },
  { year: 1945, month: 2, day: 13, animal: "Rooster", element: "Wood" },
  { year: 1946, month: 2, day: 2, animal: "Dog", element: "Fire" },
  { year: 1947, month: 1, day: 22, animal: "Pig", element: "Fire" },
  { year: 1948, month: 2, day: 10, animal: "Rat", element: "Earth" },
  { year: 1949, month: 1, day: 29, animal: "Ox", element: "Earth" },
  { year: 1950, month: 2, day: 17, animal: "Tiger", element: "Metal" },
  { year: 1951, month: 2, day: 6, animal: "Rabbit", element: "Metal" },
  { year: 1952, month: 1, day: 27, animal: "Dragon", element: "Water" },
  { year: 1953, month: 2, day: 14, animal: "Snake", element: "Water" },
  { year: 1954, month: 2, day: 3, animal: "Horse", element: "Wood" },
  { year: 1955, month: 1, day: 24, animal: "Goat", element: "Wood" },
  { year: 1956, month: 2, day: 12, animal: "Monkey", element: "Fire" },
  { year: 1957, month: 1, day: 31, animal: "Rooster", element: "Fire" },
  { year: 1958, month: 2, day: 18, animal: "Dog", element: "Earth" },
  { year: 1959, month: 2, day: 8, animal: "Pig", element: "Earth" },
  { year: 1960, month: 1, day: 28, animal: "Rat", element: "Metal" },
  { year: 1961, month: 2, day: 15, animal: "Ox", element: "Metal" },
  { year: 1962, month: 2, day: 5, animal: "Tiger", element: "Water" },
  { year: 1963, month: 1, day: 25, animal: "Rabbit", element: "Water" },
  { year: 1964, month: 2, day: 13, animal: "Dragon", element: "Wood" },
  { year: 1965, month: 2, day: 2, animal: "Snake", element: "Wood" },
  { year: 1966, month: 1, day: 21, animal: "Horse", element: "Fire" },
  { year: 1967, month: 2, day: 9, animal: "Goat", element: "Fire" },
  { year: 1968, month: 1, day: 30, animal: "Monkey", element: "Earth" },
  { year: 1969, month: 2, day: 17, animal: "Rooster", element: "Earth" },
  { year: 1970, month: 2, day: 6, animal: "Dog", element: "Metal" },
  { year: 1971, month: 1, day: 27, animal: "Pig", element: "Metal" },
  { year: 1972, month: 2, day: 15, animal: "Rat", element: "Water" },
  { year: 1973, month: 2, day: 3, animal: "Ox", element: "Water" },
  { year: 1974, month: 1, day: 23, animal: "Tiger", element: "Wood" },
  { year: 1975, month: 2, day: 11, animal: "Rabbit", element: "Wood" },
  { year: 1976, month: 1, day: 31, animal: "Dragon", element: "Fire" },
  { year: 1977, month: 2, day: 18, animal: "Snake", element: "Fire" },
  { year: 1978, month: 2, day: 7, animal: "Horse", element: "Earth" },
  { year: 1979, month: 1, day: 28, animal: "Goat", element: "Earth" },
  { year: 1980, month: 2, day: 16, animal: "Monkey", element: "Metal" },
  { year: 1981, month: 2, day: 5, animal: "Rooster", element: "Metal" },
  { year: 1982, month: 1, day: 25, animal: "Dog", element: "Water" },
  { year: 1983, month: 2, day: 13, animal: "Pig", element: "Water" },
  { year: 1984, month: 2, day: 2, animal: "Rat", element: "Wood" },
  { year: 1985, month: 2, day: 20, animal: "Ox", element: "Wood" },
  { year: 1986, month: 2, day: 9, animal: "Tiger", element: "Fire" },
  { year: 1987, month: 1, day: 29, animal: "Rabbit", element: "Fire" },
  { year: 1988, month: 2, day: 17, animal: "Dragon", element: "Earth" },
  { year: 1989, month: 2, day: 6, animal: "Snake", element: "Earth" },
  { year: 1990, month: 1, day: 27, animal: "Horse", element: "Metal" },
  { year: 1991, month: 2, day: 15, animal: "Goat", element: "Metal" },
  { year: 1992, month: 2, day: 4, animal: "Monkey", element: "Water" },
  { year: 1993, month: 1, day: 23, animal: "Rooster", element: "Water" },
  { year: 1994, month: 2, day: 10, animal: "Dog", element: "Wood" },
  { year: 1995, month: 1, day: 31, animal: "Pig", element: "Wood" },
  { year: 1996, month: 2, day: 19, animal: "Rat", element: "Fire" },
  { year: 1997, month: 2, day: 7, animal: "Ox", element: "Fire" },
  { year: 1998, month: 1, day: 28, animal: "Tiger", element: "Earth" },
  { year: 1999, month: 2, day: 16, animal: "Rabbit", element: "Earth" },
  { year: 2000, month: 2, day: 5, animal: "Dragon", element: "Metal" },
  { year: 2001, month: 1, day: 24, animal: "Snake", element: "Metal" },
  { year: 2002, month: 2, day: 12, animal: "Horse", element: "Water" },
  { year: 2003, month: 2, day: 1, animal: "Goat", element: "Water" },
  { year: 2004, month: 1, day: 22, animal: "Monkey", element: "Wood" },
  { year: 2005, month: 2, day: 9, animal: "Rooster", element: "Wood" },
  { year: 2006, month: 1, day: 29, animal: "Dog", element: "Fire" },
  { year: 2007, month: 2, day: 18, animal: "Pig", element: "Fire" },
  { year: 2008, month: 2, day: 7, animal: "Rat", element: "Earth" },
  { year: 2009, month: 1, day: 26, animal: "Ox", element: "Earth" },
  { year: 2010, month: 2, day: 14, animal: "Tiger", element: "Metal" },
  { year: 2011, month: 2, day: 3, animal: "Rabbit", element: "Metal" },
  { year: 2012, month: 1, day: 23, animal: "Dragon", element: "Water" },
  { year: 2013, month: 2, day: 10, animal: "Snake", element: "Water" },
  { year: 2014, month: 1, day: 31, animal: "Horse", element: "Wood" },
  { year: 2015, month: 2, day: 19, animal: "Goat", element: "Wood" },
  { year: 2016, month: 2, day: 8, animal: "Monkey", element: "Fire" },
  { year: 2017, month: 1, day: 28, animal: "Rooster", element: "Fire" },
  { year: 2018, month: 2, day: 16, animal: "Dog", element: "Earth" },
  { year: 2019, month: 2, day: 5, animal: "Pig", element: "Earth" },
  { year: 2020, month: 1, day: 25, animal: "Rat", element: "Metal" },
  { year: 2021, month: 2, day: 12, animal: "Ox", element: "Metal" },
  { year: 2022, month: 2, day: 1, animal: "Tiger", element: "Water" },
  { year: 2023, month: 1, day: 22, animal: "Rabbit", element: "Water" },
  { year: 2024, month: 2, day: 10, animal: "Dragon", element: "Wood" },
  { year: 2025, month: 1, day: 29, animal: "Snake", element: "Wood" },
  { year: 2026, month: 2, day: 17, animal: "Horse", element: "Fire" },
  { year: 2027, month: 2, day: 6, animal: "Goat", element: "Fire" },
  { year: 2028, month: 1, day: 26, animal: "Monkey", element: "Earth" },
  { year: 2029, month: 2, day: 13, animal: "Rooster", element: "Earth" }
];
